In [1]:
import pandas as pd
import numpy as np

In [3]:
ipl=pd.read_csv('IPL.csv')

C:\Users\Saksham\AppData\Local\Temp\ipykernel_25508\2676402325.py:1: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  ipl=pd.read_csv('IPL.csv')

In [4]:
ipl.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,131970,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,131971,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,131972,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,131973,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,131974,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [12]:
ipl=ipl[['match_id','city','match_won_by','runs_total','innings']]
total_score_df = ipl.groupby(['match_id','innings','match_won_by'])['runs_total'].sum().reset_index()
#total_score_df = total_score_df[total_score_df['innings'] == 1]
total_score_df

      match_id  innings                 match_won_by  runs_total
0       335982        1        Kolkata Knight Riders         222
1       335982        2        Kolkata Knight Riders          82
2       335983        1          Chennai Super Kings         240
3       335983        2          Chennai Super Kings         207
4       335984        1             Delhi Daredevils         129
...        ...      ...                          ...         ...
2360   1473510        2                 Punjab Kings         207
2361   1473511        1  Royal Challengers Bengaluru         190
2362   1473511        2  Royal Challengers Bengaluru         184
2363   1485779        1               Delhi Capitals         206
2364   1485779        2               Delhi Capitals         208

[2365 rows x 4 columns]

In [ ]:
teams = [
    'Sunrisers Hyderabad',
    'Mumbai Indians',
    'Royal Challengers Bangalore',
    'Kolkata Knight Riders',
    'Kings XI Punjab',
    'Chennai Super Kings',
    'Rajasthan Royals',
    'Delhi Capitals',
    'Lucknow Super Giants',
    'Gujarat Titans'
]

In [ ]:
match_df['team1'] = match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2'] = match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

match_df['team1'] = match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2'] = match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

match_df['team1'] = match_df['team1'].str.replace('Kings XI Punjab','Punjab Kings')
match_df['team2'] = match_df['team2'].str.replace('Kings XI Punjab','Punjab Kings')